### ISSUE TITLE
Documentation Improvements Checklist

### ISSUE THREAD

**Issue by Zeenobit** [Zeenobit/moonshine_save#4]
## TODO

- [x] Document the rationale behind the design in more depth
- [ ] Links to alternative save libraries
- [x] Simplified examples
    - [x] Fix Copy Paste errors in documentation examples
